config/routes.rb
Subz::Application.routes.draw do

  post '/data' => 'home#data'
  match '/entrances' => 'home#entrances'
  post '/plot' => 'home#plot'
  post '/search' => 'home#search'

  

  root :to => 'home#index'

end

app/models/entrance.rb
# == Schema Information
#
# Table name: entrances
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  lat        :decimal(, )
#  long       :decimal(, )
#  line       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Entrance < ActiveRecord::Base
	belongs_to :subway

	def self.text_search(query) #this makes a class method that gets used in the controller
  	self.where("name @@ :q or description @@ :q", :q => query)
  end
end

app/models/subway.rb
# == Schema Information
#
# Table name: subways
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  latitude   :float
#  longitude  :float
#  line       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subway < ActiveRecord::Base
	def self.text_search(query)
       self.where("name @@ :q or line @@ :q", :q => query)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

		@entrances = Subway.all

	end

	def entrances
	Subway.delete_all
    x = HTTParty.get('http://data.cityofnewyork.us/api/views/drex-xx56/rows.json')
    y = JSON(x.body)
    y["data"].each do |t|
      lines_array = t.last.split('-')
      lines_array.each do |f|
        point = t[9][5]["point"]
        s = Subway.create(:name=> t[10], :latitude => point[1], :longitude => point[0], :line => f)      
      end
    end
    @entrances = Subway.all

	end

	def plot
		@subways = Subway.where(:line => params[:commit])
	end

	 def search
    	@subways = Subway.text_search(params[:commit])
  	end
		
end

app/helpers/application_helper.rb
module ApplicationHelper


	def subway_line(arg)

		@hello = Entrance.where(:line => arg )
		
		

	end


end

app/views/home/_map.html.erb
<div id="map_canvas"></div>

<script>
	display_map(<%=lat%>,<%=long%>,<%=zoom%>);
</script>

app/views/home/entrances.html.erb
<div class="float">
<%= form_tag plot_path, :remote => true do %>
	<% Subway.find(:all, :select => "distinct line").each do |t| %>
		<%= submit_tag t.line, class: "btn btn-primary" %>
	<% end %>
<% end %>
</div>

<div id="map_container">
<%= render :partial => 'map', :locals => {:lat => 40.7, :long => -73.98, :zoom => 12} %>
</div>

<%= form_tag search_path, :remote => true do %>
	<%= label_tag 'search' %>
	<%= text_field_tag 'commit' %>
<% end %>

app/views/home/index.html.erb
<%= button_to 'Get Subway Data', '/entrances', class: "btn btn-primary" %>

app/views/home/show.html.erb
<%= button_to 'Get Data', '/data' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{GOOGLEKEY}&sensor=false" %>
  <link href='http://fonts.googleapis.com/css?family=Rambla' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
  		<h1>subz</h1>
  		<p>You're welcome New York</p>
	</header>
<%= yield %>

<footer></footer>
</body>
</html>